project:
  type: website
  output-dir: docs

website:
  title: "Krishnatheja Vanka"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/theja-vanka
format:
  html:
    theme: 
    - cosmo
    - style.scss    
    css: styles.css



