project:
  type: website
  output-dir: docs
execute:
  freeze: auto
website:
  title: "Krishnatheja Vanka's Blog"
  favicon: favicon.ico
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/theja-vanka
  page-footer:
    center: "© 2025 Krishnatheja Vanka"
format:
  html:
    theme:
      light: [cosmo, styles/custom.scss]
      dark: [cosmo, styles/theme-dark.scss]
    css: styles/styles.css
    page-layout: full
    toc: true
    toc-location: left
    code-copy: true



